# Generated by Django 5.0.6 on 2024-10-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alert',
        ),
    ]
