# Generated by Django 5.0.6 on 2024-11-04 05:09

import utilities.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_image',
            field=models.ImageField(blank=True, default='alert/alerts/dummy-profile-pic.png', null=True, upload_to='alert/alerts', validators=[utilities.validators.validators.image_file_validator]),
        ),
    ]
