# Generated by Django 5.0.6 on 2024-11-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alter_alert_alert_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_image',
        ),
    ]
