# Generated by Django 5.0.6 on 2024-11-04 06:20

import utilities.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_remove_alert_alert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_image',
            field=models.ImageField(blank=True, default='alert/alert.jpg', null=True, upload_to='alert', validators=[utilities.validators.validators.image_file_validator]),
        ),
    ]
