# Generated by Django 5.0.6 on 2024-10-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_alter_employee_date_of_birth_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
