# Generated by Django 5.0.6 on 2024-10-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0003_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
