# Generated by Django 5.0.6 on 2024-10-21 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0004_alter_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('In a Relationship', 'In a Relationship'), ('Engaged', 'Engaged')], max_length=100, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_children', models.IntegerField(blank=True, null=True)),
                ('child_one_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_one_age', models.IntegerField(blank=True, null=True)),
                ('child_two_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_two_age', models.IntegerField(blank=True, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('current_address', models.CharField(blank=True, max_length=200, null=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternate_contact', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, choices=[('BTech', 'Bachelor of Technology (B.Tech)'), ('MTech', 'Master of Technology (M.Tech)'), ('BCA', 'Bachelor of Computer Applications (BCA)'), ('MCA', 'Master of Computer Applications (MCA)'), ('BBA', 'Bachelor of Business Administration (BBA)'), ('MBA', 'Master of Business Administration (MBA)'), ('BSc', 'Bachelor of Science (B.Sc)'), ('MSc', 'Master of Science (M.Sc)'), ('BA', 'Bachelor of Arts (BA)'), ('MA', 'Master of Arts (MA)'), ('Diploma', 'Diploma'), ('Diploma in Engineering', 'Diploma in Engineering'), ('Diploma in Computer Science', 'Diploma in Computer Science'), ('Diploma in Information Technology', 'Diploma in Information Technology'), ('Diploma in Business Management', 'Diploma in Business Management'), ('Diploma in Hospitality Management', 'Diploma in Hospitality Management'), ('Diploma in Graphic Design', 'Diploma in Graphic Design'), ('Certificate', 'Certificate'), ('Certificate in Digital Marketing', 'Certificate in Digital Marketing'), ('Certificate in Web Development', 'Certificate in Web Development'), ('Certificate in Data Science', 'Certificate in Data Science'), ('Certificate in Graphic Design', 'Certificate in Graphic Design'), ('Certificate in Project Management', 'Certificate in Project Management'), ('Certificate in Cyber Security', 'Certificate in Cyber Security')], max_length=100, null=True)),
                ('stream', models.CharField(blank=True, choices=[('Science', 'Science Division'), ('Commerce', 'Commerce Division'), ('Arts', 'Arts Division'), ('Engineering', 'Engineering Division'), ('Management', 'Management Division')], max_length=100, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('division', models.CharField(blank=True, choices=[('First', 'First Division'), ('Second', 'Second Division'), ('Third', 'Third Division')], max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_qualification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('C#', 'C#'), ('SQL', 'SQL'), ('HTML/CSS', 'HTML/CSS'), ('Data Analysis', 'Data Analysis'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Graphic Design', 'Graphic Design'), ('User Experience (UX)', 'User Experience (UX)'), ('Project Management', 'Project Management'), ('Agile Methodologies', 'Agile Methodologies'), ('Communication', 'Communication'), ('Problem Solving', 'Problem Solving'), ('Teamwork', 'Teamwork'), ('Adaptability', 'Adaptability'), ('Leadership', 'Leadership'), ('Creativity', 'Creativity'), ('Public Speaking', 'Public Speaking'), ('Time Management', 'Time Management'), ('Networking', 'Networking'), ('Cloud Computing', 'Cloud Computing'), ('DevOps', 'DevOps'), ('Cybersecurity', 'Cybersecurity'), ('SEO', 'Search Engine Optimization (SEO)'), ('Digital Marketing', 'Digital Marketing'), ('Content Writing', 'Content Writing'), ('Foreign Language Proficiency', 'Foreign Language Proficiency'), ('Sales Skills', 'Sales Skills'), ('Customer Service', 'Customer Service')], max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
