# Generated by Django 5.0.6 on 2024-10-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0005_employeeprofile_employeequalification_employeeskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='customer',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeequalification',
            old_name='customer',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeeskills',
            old_name='customer',
            new_name='employee',
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table='employee_profile',
        ),
        migrations.AlterModelTable(
            name='employeequalification',
            table='employee_qualification',
        ),
        migrations.AlterModelTable(
            name='employeeskills',
            table='employee_skill',
        ),
    ]
