# Generated by Django 5.0.6 on 2024-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0006_rename_customer_employeeprofile_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=100, null=True),
        ),
    ]
