# Generated by Django 5.0.6 on 2024-10-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0007_employeeprofile_blood_group'),
        ('attendance', '0007_alter_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees_department', to='attendance.department'),
            preserve_default=False,
        ),
    ]
