# Generated by Django 5.0.6 on 2024-10-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0009_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
    ]
