# Generated by Django 5.0.6 on 2024-10-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0012_alter_employeeprofile_department'),
        ('attendance', '0007_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employees_department', to='attendance.department'),
        ),
    ]
