# Generated by Django 5.0.6 on 2024-10-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0013_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeequalification',
            name='degree',
            field=models.CharField(blank=True, choices=[('BTech', 'Bachelor of Technology (B.Tech)'), ('MTech', 'Master of Technology (M.Tech)'), ('BCA', 'Bachelor of Computer Applications (BCA)'), ('MCA', 'Master of Computer Applications (MCA)'), ('BBA', 'Bachelor of Business Administration (BBA)'), ('MBA', 'Master of Business Administration (MBA)'), ('BSc', 'Bachelor of Science (B.Sc)'), ('MSc', 'Master of Science (M.Sc)'), ('B.Com(H)', 'Bachelor of Commerce Hounors (B.Com(H))'), ('M.Com(H)', 'Master of Commerce Hounors (M.Com(H))'), ('B.Com', 'Bachelor of Commerce (B.Com)'), ('M.Com', 'Master of Commerce (M.Com)'), ('BA', 'Bachelor of Arts (BA)'), ('MA', 'Master of Arts (MA)'), ('Diploma', 'Diploma'), ('Diploma in Engineering', 'Diploma in Engineering'), ('Diploma in Computer Science', 'Diploma in Computer Science'), ('Diploma in Information Technology', 'Diploma in Information Technology'), ('Diploma in Business Management', 'Diploma in Business Management'), ('Diploma in Hospitality Management', 'Diploma in Hospitality Management'), ('Diploma in Graphic Design', 'Diploma in Graphic Design'), ('Certificate', 'Certificate'), ('Certificate in Digital Marketing', 'Certificate in Digital Marketing'), ('Certificate in Web Development', 'Certificate in Web Development'), ('Certificate in Data Science', 'Certificate in Data Science'), ('Certificate in Graphic Design', 'Certificate in Graphic Design'), ('Certificate in Project Management', 'Certificate in Project Management'), ('Certificate in Cyber Security', 'Certificate in Cyber Security')], max_length=100, null=True),
        ),
    ]
