# Generated by Django 5.0.6 on 2024-10-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0014_alter_employeequalification_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
