# Generated by Django 5.0.6 on 2024-11-04 06:55

import utilities.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0015_alter_employee_options_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, default='user/dummy-profile-pic.jpg', null=True, upload_to='user', validators=[utilities.validators.validators.image_file_validator]),
        ),
    ]
