# Generated by Django 5.0.6 on 2024-10-22 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
