# Generated by Django 5.0.6 on 2024-10-23 09:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_total_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('holiday', models.CharField(choices=[("New Year's Day", "New Year's Day"), ('Makar Sankranti', 'Makar Sankranti'), ('Republic Day', 'Republic Day'), ('Holi', 'Holi'), ('Good Friday', 'Good Friday'), ('Baisakhi', 'Baisakhi'), ('Labour Day', 'Labour Day'), ('Eid al-Adha', 'Eid al-Adha'), ('Independence Day', 'Independence Day'), ('National Sports Day', 'National Sports Day'), ('Ganesh Chaturthi', 'Ganesh Chaturthi'), ('Gandhi Jayanti', 'Gandhi Jayanti'), ('Diwali', 'Diwali'), ('Guru Nanak Jayanti', 'Guru Nanak Jayanti'), ('Christmas', 'Christmas')], max_length=200)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
    ]
