# Generated by Django 5.0.6 on 2024-10-24 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
