# Generated by Django 5.0.6 on 2024-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
