# Generated by Django 5.0.6 on 2024-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('First Half', 'First Half'), ('Second Half', 'Second Half'), ('Week Off', 'Week Off')], default='Present', max_length=50),
        ),
    ]
