# Generated by Django 5.0.6 on 2024-10-25 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_employeeleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedLeaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Emergency Leave', 'Emergency Leave'), ('Casual Leave', 'Casual Leave'), ('Family Leave', 'Family Leave'), ('Study Leave', 'Study Leave'), ('Marriage Leave', 'Marriage Leave'), ('Other Leave', 'Other Leave')], max_length=200)),
                ('leave_apply_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_applied_leave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
