# Generated by Django 5.0.6 on 2024-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_rename_start_date_appliedleavedata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedleavedata',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Applied', max_length=100),
        ),
    ]
