# Generated by Django 5.0.6 on 2024-10-25 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_appliedleavedata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedleavedata',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appliedleavedata',
            name='no_of_days',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='appliedleavedata',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
