# Generated by Django 5.0.6 on 2024-10-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_appliedleavedata_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedleavedata',
            name='leave_type',
            field=models.CharField(choices=[('First Half', 'First Half'), ('Second Half', 'Second Half'), ('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Emergency Leave', 'Emergency Leave'), ('Casual Leave', 'Casual Leave'), ('Family Leave', 'Family Leave'), ('Study Leave', 'Study Leave'), ('Marriage Leave', 'Marriage Leave'), ('Other Leave', 'Other Leave')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('First Half', 'First Half'), ('Second Half', 'Second Half'), ('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Emergency Leave', 'Emergency Leave'), ('Casual Leave', 'Casual Leave'), ('Family Leave', 'Family Leave'), ('Study Leave', 'Study Leave'), ('Marriage Leave', 'Marriage Leave'), ('Other Leave', 'Other Leave')], max_length=200),
        ),
    ]
