# Generated by Django 5.0.6 on 2024-10-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_appliedleavedata_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedleavedata',
            name='date',
        ),
    ]
