# Generated by Django 5.0.6 on 2024-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remove_appliedleavedata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('attendance_id', models.PositiveIntegerField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
