# Generated by Django 5.0.6 on 2024-10-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_attendancemodificationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodificationrequest',
            name='attendance_id',
        ),
    ]
